---
version: 2
registries:
  docker-elastic:
    type: docker-registry
    url: https://docker.elastic.co
    username: ${{secrets.ELASTIC_DOCKER_USERNAME}}
    password: ${{secrets.ELASTIC_DOCKER_PASSWORD}}

updates:
  # Enable version updates for python
  - package-ecosystem: "pip"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    reviewers:
      - "elastic/apm-agent-python"

  - package-ecosystem: "github-actions"
    directories:
      - '/'
      - '/.github/actions/*'
    reviewers:
      - "elastic/observablt-ci"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - '/'
      - 'operator/*'
    reviewers:
      - "elastic/apm-agent-python"
    registries: "*"
    schedule:
      interval: "daily"
    ignore:
      - update-types: ["version-update:semver-major", "version-update:semver-minor"]
