# This is a dockerfile for local testing
FROM python:3.12.12-alpine AS build

ARG DISTRO_DIR

COPY ${DISTRO_DIR} /opt/distro

WORKDIR /operator-build

ADD operator/requirements.txt .

RUN mkdir workspace

RUN apk add gcc python3-dev musl-dev linux-headers

RUN pip install --target workspace /opt/distro/*.whl -r requirements.txt

FROM python:3.12.12-alpine

COPY --from=build /operator-build/workspace /autoinstrumentation

RUN chmod -R go+r /autoinstrumentation
